### ISSUE TITLE
有关任务调度的问题

### ISSUE THREAD

**Issue by unicornx** [cccriscv/mini-riscv-os#3]
你好，
针对 05-Preemptive 这个例子，sys_timer 函数通过 mret 跳转到 sys_kernel 中去执行切换人物的工作，但我认为此时中断已经开了，我怀疑 万一在此期间发生timer interrupt 是不是会有问题？

**Comment by ccckmit** [comment]
> 你好，
> 针对 05-Preemptive 这个例子，sys_timer 函数通过 mret 跳转到 sys_kernel 中去执行切换人物的工作，但我认为此时中断已经开了，我怀疑 万一在此期间发生timer interrupt 是不是会有问题？

目前的版本我想問題還很多，我不是 RISC-V 的熟練者，主要參考 xv6 的 RISC-V 的版本寫的，確實有不少地方考慮不周！

**Comment by ccckmit** [comment]
> 你好，
> 针对 05-Preemptive 这个例子，sys_timer 函数通过 mret 跳转到 sys_kernel 中去执行切换人物的工作，但我认为此时中断已经开了，我怀疑 万一在此期间发生timer interrupt 是不是会有问题？

這期間發生中段的話，我也認為可能有問題！

不知您有沒有比較好的方法？

**Comment by ianchen0119** [comment]
@unicornx  我在想，或許在 Timer interrupt 發生時，先關閉 MIE 中的 Timer interrupt 域，等到中斷處理完成後再開啟或許可以解決你所提到的潛在問題?

**Comment by unicornx** [comment]
hi，我觉得还是在中断处理中完成任务切换比较好，此时中断是关闭的，完成切换后进入任务上下文再打开中断这样就比较安全了。基于该思想我写了一个小的 riscv 的 os 进行验证（<https://github.com/plctlab/riscv-operating-system-mooc>）。当然借鉴了您这个仓库的一些思想，在此表示非常感谢。

**Comment by ianchen0119** [comment]
@unicornx 原來您是該專案的作者!我在改寫專案時也參考了您的專案，十分受用!
